version: "3.7"

services:
  capture-api:
    image: aqi-sensor-api:latest
    container_name: aqi-sensor-api
    restart: always
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - "3500:3500"
